[package]
name = "cjdnsbox_hook"
version = "0.1.0"
authors = ["Valentin Lorentz <progval+git@progval.net>"]

[dependencies]
cjdnsbox = { path = "../cjdnsbox" }
libc = "0.2.45"
lazy_static = "1.2.0"

[lib]
name = "cjdnsbox_hook"
crate_type = ["cdylib"]
